# This is a comment
FROM ubuntu
MAINTAINER Pupi <dreamjl@live.cn>
RUN apt-get install zsh -y
RUN apt-get install git -y
RUN curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
RUN chsh -s /bin/zsh
